# Generated by Django 3.0.4 on 2020-04-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, verbose_name='Answer ID')),
                ('ans', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='Problem ID')),
                ('problem', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='Quiz ID')),
                ('quiz_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer', verbose_name='Answer ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Problem ID')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz ID'),
        ),
        migrations.AddField(
            model_name='answer',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Problem ID'),
        ),
    ]
